#ifndef _INCLUDES_H_
#define _INCLUDES_H_
//--------------------------------------------------
//		头文件
//--------------------------------------------------
#include <string.h>
#include "stm32f10x.h"
#include "main.h"
#include "misc.h"	//NVIC中断
#include "stm32f10x_it.h"
#include "stm32f10x_usart.h"
#include "stm32f10x_flash.h"
#include "..\GUI\GUI_printf.h"
#include "stm32f10x_tim.h"
#include "stm32f10x_dma.h"
#endif
